
services:

  # isaac-sim:
  #   build:
  #     context: ./dockerfiles/
  #     dockerfile: isaacsim_humble_dockerfile
  #   image: isaacsim_humble

  #   container_name: humble-isaac-sim
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - PRIVACY_CONSENT=Y
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities:
  #               - gpu
  #   volumes:
  #     - ./fastdds.xml:/root/.ros/fastdds.xml:rw
  #     # - ~/docker/isaac-sim/cache/kit:/isaac-sim/kit/cache:rw
  #     - ~/docker/isaac-sim/cache/ov:/root/.cache/ov:rw
  #     # - ~/docker/isaac-sim/cache/pip:/root/.cache/pip:rw
  #     # - ~/docker/isaac-sim/cache/glcache:/root/.cache/nvidia/GLCache:rw
  #     # - ~/docker/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw
  #     # - ~/docker/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw
  #     # - ~/docker/isaac-sim/data:/root/.local/share/ov/data:rw
  #     # - ~/docker/isaac-sim/documents:/root/Documents:rw
  #     - ./humble_ws:/isaac-sim/humble_ws:rw
  #     - ./rolling_ws/src/antworker_description/description/:/isaac-sim/rolling_ws/src/antworker_description/description/:rw
  #     - ./docker_entry_scripts/isaacsim_entrypoint.sh:/isaac-sim/scripts/isaacsim_entrypoint.sh:rw
  #   network_mode: "host"
  #   restart: "no"
  #   entrypoint: /isaac-sim/scripts/isaacsim_entrypoint.sh

  # humble-desktop-navigation:
  #   container_name: humble-desktop-navigation
  #   build:
  #     context: ./dockerfiles/
  #     dockerfile: navigation_dockerfile
  #   image: humble_dev_img
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ./humble_ws:/home/humble_ws:rw
  #     - ./docker_entry_scripts/dev_entrypoint.sh:/isaac-sim/scripts/dev_entrypoint.sh:rw
  #     - ./fastdds.xml:/root/.ros/fastdds.xml:rw
  #   #privileged: true # Couldnt get joystick passed in with 'device' tag, so using privileged mode. TODO - pass joystick in without using privileged mode
  #   #network_mode: "host"
  #   working_dir: /home/humble_ws/src/antworker_navigation/launch
  #   restart: "no"
  #   entrypoint: /isaac-sim/scripts/dev_entrypoint.sh

  # rolling-desktop-kinova:
  #   container_name: rolling-desktop-kinova
  #   build:
  #     context: ./dockerfiles/
  #     dockerfile: kinova_dockerfile
  #   image: rolling_kinova_img
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ./rolling_ws:/home/rolling_ws:rw
  #     - ./docker_entry_scripts/kinova_entrypoint.sh:/home/scripts/kinova_entrypoint.sh:rw
  #     - ./fastdds.xml:/root/.ros/fastdds.xml:rw
  #   #network_mode: "host"
  #   working_dir: /home/rolling_ws/src/
  #   restart: "no"

  #   entrypoint: /home/scripts/kinova_entrypoint.sh

  # humble-isaacsim-interface:
  #   container_name: humble-isaacsim-interface
  #   build:
  #     context: ./dockerfiles/
  #     dockerfile: joint_forwarder_dockerfile
  #   image: humble_dev_img
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ./humble_ws:/home/humble_ws:rw
  #     - ./docker_entry_scripts/joint_state_translater_entrypoint.sh:/home/scripts/joint_state_translater_entrypoint.sh:rw
  #   #network_mode: "host"
  #   working_dir: /home/humble_ws
  #   restart: "no"
  #   entrypoint: /home/scripts/joint_state_translater_entrypoint.sh

  humble-kinova:
    container_name: humble-kinova
    build:
      context: ./dockerfiles/
      dockerfile: kinova_humble_dockerfile
    image: kinova_humble
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./humble_ws:/home/humble_ws:rw
      - ./moveit:/home/moveit:rw
      - ./docker_entry_scripts/joint_state_translater_entrypoint.sh:/home/scripts/joint_state_translater_entrypoint.sh:rw
    #network_mode: "host"
    working_dir: /home/humble_ws/src
    restart: "no"
    # entrypoint: /home/scripts/joint_state_translater_entrypoint.sh