sensors:
  - default_sensor
  # - pointcloud_sensor

# default_sensor:
#   far_clipping_plane_distance: 5.0
#   filtered_cloud_topic: ""
#   image_topic: /camera/camera/depth/image_rect_raw
#   max_update_rate: 25.0
#   near_clipping_plane_distance: 0.1
#   padding_offset: 0.03 # Distance required for arm to be from obstacles
#   padding_scale: 0.01 # Scales padding based on distance to obstacle
#   queue_size: 5
#   sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#   shadow_threshold: 0.2

default_sensor:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /camera/camera/depth/color/points # nonsense_topic
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.03
  padding_scale: 0.01
  max_update_rate: 1.0
  filtered_cloud_topic: filtered_cloud
