sensors:
  - default_sensor
default_sensor:
  far_clipping_plane_distance: 2.0
  filtered_cloud_topic: ""
  image_topic: /depth
  max_update_rate: 10.0
  near_clipping_plane_distance: 0.1
  padding_offset: 0.1
  padding_scale: 0.1
  queue_size: 10
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: ""