[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "test_scripting_extension"
description = "I am trying to make an extension to create a behaviour tree"
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}

[[python.module]]
name = "test_scripting_extension_python"