<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rails">

    <xacro:arg name="world_props_path" default="$(find iris_gazebo)/config/world_props.yaml" />

    <!-- IMPORT YAML CONFIGS -->
    <xacro:property name="world_props_file" value="$(arg world_props_path)" />
    <xacro:property name="world_props" value="${xacro.load_yaml(world_props_file)}" />

    <xacro:property name="both_sides" value="${world_props['rails']['both_sides']}" />
    <xacro:property name="width" value="${world_props['rails']['width']}" />
    <xacro:property name="height" value="${world_props['rails']['height']}" />
    <xacro:property name="length" value="${world_props['rails']['length']}" />
    <xacro:property name="rail_width" value="${world_props['rails']['rail_width']}" />
    <xacro:property name="aisle_width" value="${world_props['world']['aisle_width']}" />

    <xacro:property name="x_pos" value="${length/2+aisle_width/2}" />
    <xacro:property name="bumper_length" value="0.10" />
    <xacro:property name="bumper_height" value="0.25" />

    <link name="world" />

    <link name="rails">
        <inertial>
            <origin xyz="${x_pos} 0 0" />
            <mass value="10000.0" />
            <inertia ixx="1000000.0" ixy="0.0" ixz="0.0" iyy="1000000.0" iyz="0.0" izz="1000000.0" />
        </inertial>

        <!-- visuals definitions -->
        <!-- rails -->
        <visual>
            <origin xyz="${x_pos} ${width/2-rail_width/2} 0" />
            <geometry>
                <box size="${length} ${rail_width} ${height}" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="${x_pos} ${-width/2+rail_width/2} 0" />
            <geometry>
                <box size="${length} ${rail_width} ${height}" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="${aisle_width/2} 0 0" />
            <geometry>
                <box size="${2*rail_width} ${width-2*rail_width} ${height}" />
            </geometry>
        </visual>

        <!-- rails front for easier approach -->
        <visual>
            <origin xyz="${aisle_width/2} ${width/2-rail_width} 0" />
            <geometry>
                <cylinder radius="${rail_width}" length="${height}" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="${aisle_width/2} ${-width/2+rail_width} 0" />
            <geometry>
                <cylinder radius="${rail_width}" length="${height}" />
            </geometry>
        </visual>

        <!-- bumper at the end of rails -->
        <visual>
            <origin xyz="${length+bumper_length/2+aisle_width/2} 0 ${bumper_height/2-height/2}" />
            <geometry>
                <box size="${bumper_length} ${width} ${bumper_height}" />
            </geometry>
        </visual>

        <!-- collisions definitions -->
        <!-- rails front for easier approach -->
        <collision>
            <origin xyz="${aisle_width/2} ${width/2-rail_width} 0" />
            <geometry>
                <cylinder radius="${rail_width}" length="${height}" />
            </geometry>
        </collision>
        <collision>
            <origin xyz="${aisle_width/2} ${-width/2+rail_width} 0" />
            <geometry>
                <cylinder radius="${rail_width}" length="${height}" />
            </geometry>
        </collision>
        <!-- bumper at the end of rails -->
        <collision>
            <origin xyz="${length+bumper_length/2+aisle_width/2} 0 ${bumper_height/2-height/2}" />
            <geometry>
                <box size="${bumper_length} ${width} ${bumper_height}" />
            </geometry>
        </collision>
        <!-- rails collision -->
        <collision>
            <origin xyz="${x_pos} 0 0" />
            <geometry>
                <box size="${length} ${width} ${height}" />
            </geometry>
        </collision>
        <collision>
            <origin xyz="${aisle_width/2} 0 0" />
            <geometry>
                <box size="${2*rail_width} ${width-2*rail_width} ${height}" />
            </geometry>
        </collision>

        <!-- spawn on both sides -->
        <xacro:if value="${both_sides}">

            <xacro:property name="x_pos" value="${-length/2-aisle_width/2}" />

            <!-- visuals definitions -->
            <!-- rails -->
            <visual>
                <origin xyz="${x_pos} ${width/2-rail_width/2} 0" />
                <geometry>
                    <box size="${length} ${rail_width} ${height}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${x_pos} ${-width/2+rail_width/2} 0" />
                <geometry>
                    <box size="${length} ${rail_width} ${height}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${-aisle_width/2} 0 0" />
                <geometry>
                    <box size="${2*rail_width} ${width-2*rail_width} ${height}" />
                </geometry>
            </visual>

            <!-- rails front for easier approach -->
            <visual>
                <origin xyz="${-aisle_width/2} ${width/2-rail_width} 0" />
                <geometry>
                    <cylinder radius="${rail_width}" length="${height}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${-aisle_width/2} ${-width/2+rail_width} 0" />
                <geometry>
                    <cylinder radius="${rail_width}" length="${height}" />
                </geometry>
            </visual>

            <!-- bumper at the end of rails -->
            <visual>
                <origin xyz="${-length-bumper_length/2-aisle_width/2} 0 ${bumper_height/2-height/2}" />
                <geometry>
                    <box size="${bumper_length} ${width} ${bumper_height}" />
                </geometry>
            </visual>

            <!-- collisions definition -->
            <!-- rails front for easier approach -->
            <collision>
                <origin xyz="${-aisle_width/2} ${width/2-rail_width} 0" />
                <geometry>
                    <cylinder radius="${rail_width}" length="${height}" />
                </geometry>
            </collision>
            <collision>
                <origin xyz="${-aisle_width/2} ${-width/2+rail_width} 0" />
                <geometry>
                    <cylinder radius="${rail_width}" length="${height}" />
                </geometry>
            </collision>
            <!-- bumper at the end of rails -->
            <collision>
                <origin xyz="${-length-bumper_length/2-aisle_width/2} 0 ${bumper_height/2-height/2}" />
                <geometry>
                    <box size="${bumper_length} ${width} ${bumper_height}" />
                </geometry>
            </collision>
            <!-- rails collision -->
            <collision>
                <origin xyz="${x_pos} 0 0" />
                <geometry>
                    <box size="${length} ${width} ${height}" />
                </geometry>
            </collision>
            <collision>
                <origin xyz="${-aisle_width/2} 0 0" />
                <geometry>
                    <box size="${2*rail_width} ${width-2*rail_width} ${height}" />
                </geometry>
            </collision>

        </xacro:if>

    </link>
    <joint name="rails_joint" type="fixed">
        <origin xyz="0 0 ${height/2}" rpy="0.0 0.0 0.0" />
        <parent link="world" />
        <child link="rails" />
    </joint>
    <gazebo reference="rails">
        <mu1 value="0.000001" />
        <mu2 value="0.000001" />
        <material>Gazebo/FlatBlack</material>
    </gazebo>
</robot>