/lifecycle_manager:
  ros__parameters:
    /bond_disable_heartbeat_timeout: false
    attempt_respawn_reconnection: true
    autostart: true
    bond_respawn_max_duration: 10.0
    bond_timeout: 4.0
    diagnostic_updater:
      period: 1.0
    node_names:
    - map_server
    - planner_server
    - controller_server
    - behaviors_server
    - bt_navigator
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true
