planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0
      w_heuristic_cost: 1.0
      current_goal_checker: "simple_goal_checker" # Not sure if this is necessary, literally trying everything to get current_goal_checker to work

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True