# teleop_twist_joy_node:
#   ros__parameters:
#     axis_linear:  # Left thumb stick vertical
#       x: 1.0
#     scale_linear:
#       x: 0.7
#     scale_linear_turbo:
#       x: 1.0

#     axis_angular:  # Left thumb stick horizontal
#       yaw: 0
#     scale_angular:
#       yaw: 0.4

#     enable_button: 2  # Left trigger button
#     enable_turbo_button: 5  # Right trigger button

/teleop_twist_joy_node:
  ros__parameters:
    axis_angular:
      pitch: -1
      roll: -1
      yaw: 0
    axis_linear:
      x: 1
      y: -1
      z: -1
    enable_button: 2
    enable_turbo_button: 5
    frame: teleop_twist_joy
    inverted_reverse: false
    publish_stamped_twist: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    require_enable_button: true
    scale_angular:
      pitch: 0.0
      roll: 0.0
      yaw: 0.4
    scale_angular_turbo:
      pitch: 0.0
      roll: 0.0
      yaw: 1.0
    scale_linear:
      x: 1.0
      y: 0.0
      z: 0.0
    scale_linear_turbo:
      x: 1.0
      y: 0.0
      z: 0.0
    use_sim_time: false
