# Fine to use humble image since it is the only base image
FROM osrf/ros:humble-desktop

RUN apt install vim -y

RUN apt install ros-humble-joint-state-publisher-gui -y

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

