<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="plants">

    <xacro:arg name="world_props_path" default="$(find iris_gazebo)/config/world_props.yaml" />

    <!-- IMPORT YAML CONFIGS -->
    <xacro:property name="world_props_file" value="$(arg world_props_path)" />
    <xacro:property name="world_props" value="${xacro.load_yaml(world_props_file)}" />

    <xacro:property name="both_sides" value="${world_props['plants']['both_sides']}" />
    <xacro:property name="width" value="${world_props['plants']['width']}" />
    <xacro:property name="height" value="${world_props['plants']['height']}" />
    <xacro:property name="length" value="${world_props['plants']['length']}" />
    <xacro:property name="aisle_width" value="${world_props['world']['aisle_width']}" />

    <xacro:property name="x_pos" value="${length/2+aisle_width/2}" />
    <xacro:property name="plants_elevation" value="0.3" />

    <link name="world" />

    <link name="plants">
        <inertial>
            <origin xyz="${x_pos} 0 ${plants_elevation}" />
            <mass value="100000.0" />
            <inertia ixx="10000000.0" ixy="0.0" ixz="0.0" iyy="10000000.0" iyz="0.0" izz="10000000.0" />
        </inertial>

        <visual>
            <origin xyz="${x_pos} ${width/2-0.01} ${plants_elevation}" />
            <geometry>
                <box size="${length} 0.001 ${height}" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="${x_pos} 0 ${plants_elevation}" />
            <geometry>
                <box size="${length} 0.001 ${height}" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="${x_pos} ${-width/2+0.01} ${plants_elevation}" />
            <geometry>
                <box size="${length} 0.001 ${height}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="${x_pos} 0 ${plants_elevation}" />
            <geometry>
                <box size="${length} ${width} ${height}" />
            </geometry>
        </collision>

        <!-- spawn on both sides -->
        <xacro:if value="${both_sides}">

            <xacro:property name="x_pos" value="${-length/2-aisle_width/2}" />

            <visual>
                <origin xyz="${x_pos} ${width/2-0.01} ${plants_elevation}" />
                <geometry>
                    <box size="${length} 0.001 ${height}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${x_pos} 0 ${plants_elevation}" />
                <geometry>
                    <box size="${length} 0.001 ${height}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${x_pos} ${-width/2+0.01} ${plants_elevation}" />
                <geometry>
                    <box size="${length} 0.001 ${height}" />
                </geometry>
            </visual>

            <collision>
                <origin xyz="${x_pos} 0 ${plants_elevation}" />
                <geometry>
                    <box size="${length} ${width} ${height}" />
                </geometry>
            </collision>

        </xacro:if>

    </link>

    <link name="plant_shift">

        <xacro:property name="x_pos" value="${length/2+aisle_width/2}" />

        <inertial>
            <origin xyz="0 0 ${plants_elevation}" />
            <mass value="100000.0" />
            <inertia ixx="10000000.0" ixy="0.0" ixz="0.0" iyy="10000000.0" iyz="0.0" izz="10000000.0" />
        </inertial>

        <visual>
            <origin xyz="${x_pos} ${width/4} ${plants_elevation}" />
            <geometry>
                <box size="${length} 0.001 ${height}" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="${x_pos} ${-width/4} ${plants_elevation}" />
            <geometry>
                <box size="${length} 0.001 ${height}" />
            </geometry>
        </visual>

        <xacro:if value="${both_sides}">

            <xacro:property name="x_pos" value="${-length/2-aisle_width/2}" />

            <visual>
                <origin xyz="${x_pos} ${width/4} ${plants_elevation}" />
                <geometry>
                    <box size="${length} 0.001 ${height}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${x_pos} ${-width/4} ${plants_elevation}" />
                <geometry>
                    <box size="${length} 0.001 ${height}" />
                </geometry>
            </visual>

        </xacro:if>
    </link>

    <link name="pot">

        <xacro:property name="x_pos" value="${length/2+aisle_width/2}" />

        <inertial>
            <origin xyz="${x_pos} 0 ${plants_elevation-0.05}" />
            <mass value="100000.0" />
            <inertia ixx="10000000.0" ixy="0.0" ixz="0.0" iyy="10000000.0" iyz="0.0" izz="10000000.0" />
        </inertial>

        <visual>
            <origin xyz="${x_pos} 0 ${plants_elevation-0.05}" />
            <geometry>
                <box size="${length} ${width} 0.1" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="${x_pos} 0 ${plants_elevation-0.05}" />
            <geometry>
                <box size="${length} ${width} 0.1" />
            </geometry>
        </collision>

        <xacro:if value="${both_sides}">

            <xacro:property name="x_pos" value="${-length/2-aisle_width/2}" />

            <visual>
                <origin xyz="${x_pos} 0 ${plants_elevation-0.05}" />
                <geometry>
                    <box size="${length} ${width} 0.1" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="${x_pos} 0 ${plants_elevation-0.05}" />
                <geometry>
                    <box size="${length} ${width} 0.1" />
                </geometry>
            </collision>

        </xacro:if>

    </link>

    <joint name="plants_joint" type="fixed">
        <origin xyz="0 0 ${height/2}" rpy="0.0 0.0 0.0" />
        <parent link="world" />
        <child link="plants" />
    </joint>
    <joint name="plant_shift_joint" type="fixed">
        <origin xyz="0.005 0 0" rpy="0.0 0.0 0.0" />
        <parent link="plants" />
        <child link="plant_shift" />
    </joint>
    <gazebo reference="plants">
        <material>plant/Difuse</material>
        <visual>
            <transparency>0.01</transparency>
        </visual>
    </gazebo>
    <gazebo reference="plant_shift">
        <material>plant_shift/Difuse</material>
        <visual>
            <transparency>0.01</transparency>
        </visual>
    </gazebo>

    <joint name="pot_joint" type="fixed">
        <origin xyz="0 0 -${height/2}" rpy="0.0 0.0 0.0" />
        <parent link="plants" />
        <child link="pot" />
    </joint>
    <gazebo reference="pot">
        <material>Gazebo/White</material>
    </gazebo>

</robot>